module(name="exaudfclient", version = "1.0")

bazel_dep(name = "exaudfclient_base", version = "1.0.0")
git_override(
    module_name = "exaudfclient_base",
    remote = "https://github.com/exasol/udf-runner-cpp.git",
    commit = "fe4ca609677c556fafb99b2be0501203843d850f",
    strip_prefix = "udf-runner-cpp/v1/base",
    patches = ["//:patches/udf_runner_cpp_build.patch"],
    patch_args = ["-p0"],
)
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_shell", version = "0.8.0")

numpy_local_repository = use_repo_rule("//base:python_repository.bzl", "numpy_local_repository")
numpy_local_repository(name = "numpy")

python_local_repository = use_repo_rule("//base:python_repository.bzl", "python_local_repository")
python_local_repository(name = "python3", python_version="python3")

zmq_local_repository = use_repo_rule("@exaudfclient_base//:zmq_repository.bzl", "zmq_local_repository")
zmq_local_repository(name = "zmq")

protobuf_local_repository = use_repo_rule("@exaudfclient_base//:protobuf_repository.bzl", "protobuf_local_repository")
protobuf_local_repository(name = "protobuf")
