name: Check Bazel Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  USE_BAZEL_VERSION: 8.3.1
  UDF_CLIENT_ENV_FILE: /tmp/.udf_client_env
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Search for duplicated error codes
        run: bash find_duplicate_error_codes.sh

      - name: Install UDF Client Dependencies
        run: |
          sudo bash scripts/installUdfClientDeps.sh "$UDF_CLIENT_ENV_FILE"

      - name: Build
        run: |
          source "$UDF_CLIENT_ENV_FILE"
          bazel build --lockfile_mode=off --config no-tty -c dbg --config python --config fast-binary --verbose_failures
        working-directory: ./exaudfclient/